### PR TITLE
Get query file and udf file from command line. 

### PR DESCRIPTION
**Pull request by taegyunkim**
@anirudhSK 
example_queries have three folders and each folder has inputs and outputs. README files in each folder also has instructions how they were generated.

### CODE REVIEW

**Comment by anirudhSK** [comment]
@taegyunkim:

Good work! This command line interface looks much cleaner and is quite close to what we want. I don't see an example of an aggregation function as part of the groupby though.

Are we currently assuming that when we write a groupby (e.g., GROUP BY a.service_name in example_queries/group_by/query.cql), the query system will return a count of traces for every distinct value of a.service_name? In other words, is count the default aggregation function for groupby?

Also, what is the current state of how "runnable" these queries are? Which of these can be run on a service mesh with Istio/Envoy proxies, using your current hand-written Go server? And which of these needs modifications to the Go server or a full-blown REDIS-type backend in order to be executed?

**Comment by taegyunkim** [comment]
> @taegyunkim:
> 
> Good work! This command line interface looks much cleaner and is quite close to what we want. I don't see an example of an aggregation function as part of the groupby though.

> 
> Are we currently assuming that when we write a groupby (e.g., GROUP BY a.service_name in example_queries/group_by/query.cql), the query system will return a count of traces for every distinct value of a.service_name? In other words, is count the default aggregation function for groupby?

I currently assume count as default aggregation function. We want to specify aggregation function right? 

> 
> Also, what is the current state of how "runnable" these queries are? Which of these can be run on a service mesh with Istio/Envoy proxies, using your current hand-written Go server? And which of these needs modifications to the Go server or a full-blown REDIS-type backend in order to be executed?

return and udf should work on the demo. As groupby isn't yet fully specified and implemented, we'd need some more work for it.

**Comment by taegyunkim** [comment]
@anirudhSK 
For specifying aggregation functions, how about following syntax?

`MATCH ... WHERE ... GROUP <property or function call>  BY <another function>`

Here <property or function call> would refer to a simple node/graph property, or a user defined function call which takes the target trace graph, and returns a value, then we run another function to aggregate.

**Comment by anirudhSK** [comment]
This query syntax sounds reasonable to me. When you use group by a function
call (i.e., the first of the two functions in your syntax) do you mean
group by the property that is computed by the function call? What if the
function call computes multiple properties. These are all interesting
possibilities for which we can assign semantics.

For now though, it might be simpler to just do GROUP property BY function
so that we don’t yet have to deal with grouping using functions and
functions are used for aggregation alone.

**Comment by taegyunkim** [comment]
In that case, the first would return a single value for each request, but you can model multiple values as a tuple (or a fixed sized array. 

OK, I'll merge this PR and modify the group by syntax to support `GROUP property BY function`

**Comment by anirudhSK** [comment]
On Mon, Aug 31, 2020 at 10:11 AM Taegyun Kim <notifications@github.com>
wrote:

>
>
> In that case, the first would return a single value for each request, but
> you can model multiple values as a tuple (or a fixed sized array.
>
>
OK. That interpretation seems quite reasonable. Let’s do GROUPBY in stages
though. First with just grouping by node properties followed by an
aggregation function. Then if needed we can add grouping by functions based
on your semantics above.

**Pull request merged**
